"""Phase 1.3: case-study verification.

For each :data:`dark_arts.ingest.form4.CASE_STUDIES` entry, downloads the
registered filing-date window, parses every Form 4, and reports:

  * whether the parsed ``issuer_name`` matches the registry value (catches
    wrong CIK lookups),
  * how many submissions / transaction rows landed,
  * the distribution of transaction codes (A = grant/award, M = exercise,
    F = withholding, S = sale, P = purchase, D = disposition, ...),
  * whether at least one grant-coded (``A``) transaction appears on the
    derivative table — that's the PSU/RSU/options signal we expect to find.

Re-runnable: ``Portfolio.download_submissions`` is idempotent
(``skip_existing=True`` by default), so a second pass is parse-only.

Writes a markdown summary to ``docs/case_study_verification.md`` for the
record + leaves the parsed rows in memory so a follow-up parquet write
(item 4) can consume them.
"""
from __future__ import annotations

import sys
from collections import Counter
from dataclasses import dataclass

import polars as pl

from dark_arts.ingest.form4 import CASE_STUDIES, CaseStudy, ingest_case_study
from dark_arts.parse.form4 import Form4Row, form4_rows_to_frame
from dark_arts.paths import DOCS


@dataclass
class VerifyResult:
    study: CaseStudy
    n_submissions: int
    n_rows: int
    parsed_issuer_names: set[str]
    parsed_tickers: set[str]
    code_counts: Counter[str]
    derivative_grant_count: int  # rows with table_kind=='derivative' and code=='A'
    non_derivative_grant_count: int  # rows with table_kind=='non_derivative' and code=='A'

    @property
    def issuer_name_matches(self) -> bool:
        # Form 4 issuerName casing/punctuation is sometimes inconsistent across
        # filings within the same issuer (commas, periods, spacing). Match
        # against any parsed name with whitespace/punct normalized.
        norm_expected = _norm(self.study.issuer_name)
        return any(_norm(n) == norm_expected for n in self.parsed_issuer_names)


def _norm(s: str) -> str:
    return "".join(ch for ch in s.upper() if ch.isalnum())


def _verify_one(study: CaseStudy) -> VerifyResult:
    # ingest_case_study downloads the registered window but iter_form4_rows
    # walks every tar in the per-CIK cache (which may span wider windows
    # from earlier ad-hoc spot checks). Filter back down to the registered
    # window so the verification report reflects only what the registry
    # promises to capture.
    start, end = study.filing_date_window
    rows: list[Form4Row] = [
        r for r in ingest_case_study(study)
        if r.get("filed_at") and start <= r["filed_at"] <= end
    ]
    if not rows:
        return VerifyResult(
            study=study,
            n_submissions=0,
            n_rows=0,
            parsed_issuer_names=set(),
            parsed_tickers=set(),
            code_counts=Counter(),
            derivative_grant_count=0,
            non_derivative_grant_count=0,
        )

    df = form4_rows_to_frame(rows)
    return VerifyResult(
        study=study,
        n_submissions=df["accession_number"].n_unique(),
        n_rows=df.height,
        parsed_issuer_names={n for n in df["issuer_name"].unique().to_list() if n},
        parsed_tickers={t for t in df["issuer_ticker"].unique().to_list() if t},
        code_counts=Counter(c for c in df["transaction_code"].to_list() if c),
        derivative_grant_count=df.filter(
            (pl.col("table_kind") == "derivative") & (pl.col("transaction_code") == "A")
        ).height,
        non_derivative_grant_count=df.filter(
            (pl.col("table_kind") == "non_derivative") & (pl.col("transaction_code") == "A")
        ).height,
    )


def _format_report(results: list[VerifyResult]) -> str:
    lines = [
        "# Case-study verification (Phase 1.3)",
        "",
        "Auto-generated by `scripts/verify_case_studies.py` — do not hand-edit; "
        "manual spot-check findings live in [`case_study_findings.md`]"
        "(case_study_findings.md). One row per "
        "`dark_arts.ingest.form4.CASE_STUDIES` entry.",
        "",
        "**Caveat on the grants column**: the deriv / non-deriv split is *not* "
        "a reliable PSU vs RSU signal — issuers classify inconsistently (e.g. "
        "EKSO codes its PSUs as straight Common-Stock awards on the "
        "non-derivative table). Use it only as a row-count sanity check; "
        "grant_type comes from footnote analysis in step 5.",
        "",
        "| Ticker | CIK | Window | Subs | Tx | Issuer match | Grants (deriv / non-deriv) | Codes |",
        "|---|---|---|---:|---:|---|---:|---|",
    ]
    for r in results:
        cs = r.study
        match = "✅" if r.issuer_name_matches else f"❌ got {sorted(r.parsed_issuer_names)!r}"
        codes = ", ".join(f"{c}:{n}" for c, n in r.code_counts.most_common())
        lines.append(
            f"| {cs.ticker} | {cs.cik} | {cs.filing_date_window[0]}..{cs.filing_date_window[1]} "
            f"| {r.n_submissions} | {r.n_rows} | {match} "
            f"| {r.derivative_grant_count} / {r.non_derivative_grant_count} "
            f"| {codes} |"
        )
    lines.append("")
    lines.append("## Notes per study")
    for r in results:
        lines.append("")
        lines.append(f"### {r.study.ticker} — {r.study.note}")
        if r.n_rows == 0:
            lines.append("- No filings parsed in window.")
            continue
        lines.append(f"- Tickers seen in filings: {sorted(r.parsed_tickers)}")
        lines.append(f"- Issuer names seen: {sorted(r.parsed_issuer_names)}")
        if not r.issuer_name_matches:
            lines.append(f"- ⚠️ Issuer mismatch: registry says `{r.study.issuer_name}`")
        if r.derivative_grant_count == 0 and r.non_derivative_grant_count == 0:
            lines.append("- ⚠️ No grant-coded (A) transactions in window — widen or shift it.")
    return "\n".join(lines) + "\n"


def main(tickers: list[str] | None = None) -> int:
    studies = list(CASE_STUDIES)
    if tickers:
        wanted = {t.upper() for t in tickers}
        studies = [cs for cs in studies if cs.ticker in wanted]
        if not studies:
            print(f"No case studies match {sorted(wanted)}", file=sys.stderr)
            return 2

    results: list[VerifyResult] = []
    for cs in studies:
        print(
            f"=> {cs.ticker} ({cs.cik}) "
            f"{cs.filing_date_window[0]}..{cs.filing_date_window[1]} ...",
            flush=True,
        )
        try:
            r = _verify_one(cs)
        except Exception as e:  # we want to log & continue per-study
            print(f"   ERROR: {e}", file=sys.stderr)
            continue
        match = "OK" if r.issuer_name_matches else "MISMATCH"
        grants = r.derivative_grant_count + r.non_derivative_grant_count
        print(
            f"   {r.n_submissions} subs / {r.n_rows} rows / issuer={match} "
            f"/ grants={grants}",
            flush=True,
        )
        results.append(r)

    out = DOCS / "case_study_verification.md"
    out.write_text(_format_report(results))
    print(f"\nReport: {out}")

    failures = [r for r in results if not r.issuer_name_matches]
    return 0 if not failures else 1


if __name__ == "__main__":
    # Optional: pass ticker(s) to verify a subset, e.g.
    #   python scripts/verify_case_studies.py EKSO KODK
    sys.exit(main(sys.argv[1:] or None))
